### ISSUE TITLE
Action window build

### ISSUE THREAD

**Issue by leo36dff** [Black-Tek/BlackTek-Server#24]
Action > Windows Build

![Captura de tela 2024-11-04 160158](https://github.com/user-attachments/assets/a004a548-9983-415a-9424-030b0ccce09e)

**Comment by Codinablack** [comment]
Could you be more specific about what your problem is? I mean you didn't even say anything except that this is an action for windows builds... when looking at my log tho, shows all my actions are building fine on windows...

For master

![image](https://github.com/user-attachments/assets/0c04fafa-c559-4898-8d6f-bfc6024e7241)


And for the only other branch WIP augments :

![image](https://github.com/user-attachments/assets/1174fbb2-11f7-4139-b8cf-b73749dec04d)


So where and what is going on that is the problem? Is that your own workflows or what?

**Comment by Codinablack** [comment]
In fact I just noticed there are 9 projects in your build.... so that is for sure not the workflows that are for black tek.
