### ISSUE TITLE
Imbuements - It does not save attributes when disconnecting and reconnecting.

### ISSUE THREAD

**Issue by soyfabi** [Black-Tek/BlackTek-Server#9]
[Added Tibia Imbuements](https://github.com/Black-Tek/BlackTek-Server/commit/3b989ceea9ebe12c20e7f75b2d68e0fe7c391ccb)
https://github.com/Black-Tek/BlackTek-Server/commit/3b989ceea9ebe12c20e7f75b2d68e0fe7c391ccb
@ohman92

I've been implementing this system on a [**TFS 1.5 Downgrade**], and the attributes, life, mana, imbue duration, everything works perfectly, there is no problem with that.

The problem occurs when you have an imbued item equipped, when you disconnect and reconnect the item it is as if it loses the attribute.

The solution is to **unequip the imbued item**, log back in, and equip it again.

Try using an **onLogin(player)** to place
**addChanceToImbuement(player, object, team)**

But I was not successful.

I leave you an example **gif**.
![Recording 2024-06-29 at 19 21 52](https://github.com/Black-Tek/BlackTek-Server/assets/91706615/fa87835b-5a59-4235-a70d-de5309db82f3)

Well the base player has Skill 10 Axe, when the Basic Slash +1 Axe imbued Mage hat is equipped it goes to 11, logging back in with the item equipped the player gets the skill to 10, unequipping it the item goes to 9.

PD: I must emphasize that I have not made any modifications, I only followed the commits to add imbuments and nothing more.

**Comment by Codinablack** [comment]
Have you tried with the latest commits? Specifically the one that is supposed to fix an issue we were having with adding and removing attributes to equipped items?

How do you know for sure you have all the commits, could you list all the commits you got the code from? Imbuements has had many commits fixing and changing things, it does not only consist of a single or even just two commits, there must be almost a dozen by now.

**Comment by soyfabi** [comment]
Yes, I have implemented all the commits.

From this commit onwards
[Feature: Imbuements! Includes Imbuement creation and full api in lua.](https://github.com/Black-Tek/BlackTek-Server/commit/e1b3f35652c7467da8a2a3cb06a04f55976b56bb)
https://github.com/Black-Tek/BlackTek-Server/commit/e1b3f35652c7467da8a2a3cb06a04f55976b56bb

all the commit that had to do with imbuement
https://github.com/Black-Tek/BlackTek-Server/commit/57c4c72fd7f8efaa17a29201b2a706c3bbb09aea

The last commit was this
https://github.com/Black-Tek/BlackTek-Server/commit/270794b2722639a8e66b405b0299209f563fbd05
and the problem persists, when you log back in with an imbued item, you lose the ability.


I tested this with clean TFS 1.5 Nekiro to check if it was an issue with my current project and the same thing happens.

**Comment by Codinablack** [comment]
https://github.com/Black-Tek/BlackTek-Server/commit/e1b3f35652c7467da8a2a3cb06a04f55976b56bb
https://github.com/Black-Tek/BlackTek-Server/commit/08d8d43ac0621bf1a1c4292072ae9d1fdbad2866
https://github.com/Black-Tek/BlackTek-Server/commit/0293ab7c0ff2b885ef8226e0839e8e0711763b33
https://github.com/Black-Tek/BlackTek-Server/commit/5364f76aebd7df866b789aa3e5c67c0e24de2a23
https://github.com/Black-Tek/BlackTek-Server/commit/99cc75b44988bd9010c7f1301956b56a0e026f66
https://github.com/Black-Tek/BlackTek-Server/commit/0c48e968eb5f01e6fee0bf334cb05dcb0991f6a8
https://github.com/Black-Tek/BlackTek-Server/commit/863f4142ee96fbe7d33ec302a28a74da2d0195f7
https://github.com/Black-Tek/BlackTek-Server/commit/422fbb5c2fd6afb733e2299dabb1a842d8a04702
https://github.com/Black-Tek/BlackTek-Server/commit/21c5ff32313acb6313e7e3b4e4e463df055e423b
https://github.com/Black-Tek/BlackTek-Server/commit/71984ba8750a52b523aeff4d546012c45e88650c
https://github.com/Black-Tek/BlackTek-Server/commit/57c4c72fd7f8efaa17a29201b2a706c3bbb09aea
https://github.com/Black-Tek/BlackTek-Server/commit/270794b2722639a8e66b405b0299209f563fbd05

Those are all the ones I know for sure that contain code related to imbuements. Please make sure you have done all of them in the correct order (they are not listed in correct order above, you will need to go by date). 

I would start with this one below first though.
This one isnt an "imbuement fix", but it is definitely needed, as it properly removes equipment during death or logout, and is most likely the one you need

https://github.com/Black-Tek/BlackTek-Server/commit/e1896243efb9156d1f4972b10c45e07b005e7c71

If this doesnt fix your problem, I suggest opening every one of those commits up in their own tab, rearranging them in the order they were applied, and applying them all one by one in order... we dont have the problem you are facing here for black tek... I assume its an issue with either serializing or just updating the client about the skills/stats change... most likely because you dont have that bug fix up there that doesnt have anything to do with imbuements.

**Comment by soyfabi** [comment]
I was looking at the commits carefully.
And I still don't have success

`
for (int32_t slot = CONST_SLOT_FIRST; slot <= CONST_SLOT_LAST; ++slot) {
    Item* item = inventory[slot];
    if (item) {
        g_moveEvents->onPlayerDeEquip(this, item, static_cast<slots_t>(slot));
        std::cout << "Check when disconnecting player: " << getName() << std::endl;
    }
}
`

On this, place a 
**std::cout << "Check when disconnecting player: " << getName() << std::endl;**

![Recording 2024-06-30 at 17 12 02](https://github.com/Black-Tek/BlackTek-Server/assets/91706615/7dfc17f9-5b8e-42fd-b046-09587235e645)

nothing at all...

Isn't a solution possible using Lua?
something like function **onLogin(player)**, That when the player logs in, if it has imbued items then the attributes are applied.

Meanwhile, I'm waiting for some other user who uses tfs 1.5 downgrade to review this imbuements system, to see if the same thing happens to them or if it's just me.

**Comment by Codinablack** [comment]
> `for (int32_t slot = CONST_SLOT_FIRST; slot <= CONST_SLOT_LAST; ++slot) { Item* item = inventory[slot]; if (item) { g_moveEvents->onPlayerDeEquip(this, item, static_cast<slots_t>(slot)); std::cout << "Check when disconnecting player: " << getName() << std::endl; } }`


That code does not exist in my imbuements. I honestly think the issue has to be with the serialization and deserialization. I would try putting prints where the imbuements are supposed to be deserialized upon login (talking about source edit) I think its in item.cpp if I remember correctly. Basically, if I were you, and everything compiled fine, just didnt save, I would put prints everywhere until I found the problem.

**Comment by soyfabi** [comment]
hmm, I made a repository and did everything again, there were a total of 12 commits in imbuements.
I followed all the steps of the commits 1 by one and the problem persists.
I don't know if sharing a repository is allowed:
https://github.com/soyfabi/TFS-1.5-Imbuements/commits/main/

![Screenshot_6](https://github.com/Black-Tek/BlackTek-Server/assets/91706615/2f8f77fa-2853-4635-8bc8-83e9f42ca15a)

![Recording 2024-07-01 at 12 18 57](https://github.com/Black-Tek/BlackTek-Server/assets/91706615/84fff0e9-c7bd-4d0b-9028-f784a6df5b25)

Let's see if someone finds a solution for tfs 1.5 later :/

**Comment by ohman92** [comment]
I’m on vacation but I took a quick look at your rep. 
I don’t know what function is adding the skills when login but I know offlinetraining in player.cpp does “sendSkill” and runs when login. And that is commented out in your rep. Maybe try to uncomment it. I’m new to programming so take my advice with that in mind 😊

**Comment by soyfabi** [comment]
Have a good vacation.
I also don't know which one is responsible for sending the skills when you log in, but that about Offline Training is about the statues, my server doesn't have those actions.

Searching for the function
**sendSkills**

It is in **protocolgame.ccp**
**void ProtocolGame::sendAddCreature(const Creature* creature, const Position& pos, int32_t stackpos, bool isLogin)**

![Screenshot_7](https://github.com/Black-Tek/BlackTek-Server/assets/91706615/c1b1d80b-dc56-4e22-9119-334f44c4a2da)

I think that this is responsible for loading the skills when you log in.

**Comment by soyfabi** [comment]
I've been testing for a while
and the imbuments of
```
Imbuement::isResist() 
Imbuement::isDamage()
ImbuementType::IMBUEMENT_TYPE_CAPACITY_BOOST :
ImbuementDecayType::IMBUEMENT_DECAY_EQUIPPED;
ImbuementDecayType::IMBUEMENT_DECAY_INFIGHT;
```
They all work great when you reconnect, the attribute remains

The ones that **don't work** are:
```
Imbuement::isSkill()
Imbuement::isSpecialSkill()
IMBUEMENT_TYPE_SPEED_BOOST:
```
I don't know what's happening, when you reconnect you don't get the attribute :/

**Comment by Codinablack** [comment]
@soyfabi Good call sharing your repository. I was able to find your problem. The problem is not with the imbuements themselves, you did a very good and thorough job at adding them to 1.5 downgrade! Well done and good for you! The issue is that inventory update is not applied during login. This is a fix that was added by sarah on TFS. Its a one liner, but it literally resolves your problem, and any other problems related to item abilities on login.

Here is the commit you are looking for, I already checked your sources to confirm you were missing this line, adding this line should 100 percent resolve your problem, if it does, please close this issue as resolved if you are able, if not, just let me know its resolved and I will close this issue.

https://github.com/otland/forgottenserver/commit/a03b30f2c8bcd04a6a96f2d25541ae03e1b06f24

Cheers!

**Comment by soyfabi** [comment]
Thank you very much, if that solved my problem 100%, thank you for your time.
Solution:
https://github.com/otland/forgottenserver/commit/a03b30f2c8bcd04a6a96f2d25541ae03e1b06f24
